on:
    push:
        branches:
            - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

# GitHub Actions workflow to deploy to Azure using azd
# To configure required secrets for connecting to Azure, simply run `azd pipeline config`

# Set up permissions for deploying with secretless Azure federated credentials
# https://learn.microsoft.com/en-us/azure/developer/github/connect-from-azure?tabs=azure-portal%2Clinux#set-up-azure-login-with-openid-connect-authentication
permissions:
    id-token: write
    contents: read

jobs:
    build:
        runs-on: ubuntu-latest
        timeout-minutes: 15
        environment: prd
        env:
            AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID}}
            AZURE_ENV_NAME: prd
            AZURE_LOCATION: australiaeast
            AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
            AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
            GH_CONTENT_TOKEN: ${{ secrets.GH_CONTENT_TOKEN }}

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install azd
              uses: Azure/setup-azd@v1.0.0

            - uses: pnpm/action-setup@v4
              name: Install pnpm
              with:
                  run_install: false

            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: 'pnpm'

            - name: Install dependencies
              run: pnpm install

            - name: Log in with Azure (Federated Credentials)
              run: |
                  azd auth login `
                    --client-id "$Env:AZURE_CLIENT_ID" `
                    --federated-credential-provider "github" `
                    --tenant-id "$Env:AZURE_TENANT_ID"
              shell: pwsh

            - name: Provision Infrastructure
              run: azd provision --no-prompt
              env:
                  AZD_INITIAL_ENVIRONMENT_CONFIG: ${{ secrets.AZD_INITIAL_ENVIRONMENT_CONFIG }}

            - name: Build application
              run: pnpm nx build website

            - name: Deploy Application
              run: azd deploy --no-prompt
